.TH DUPLICATE 1 "v\ 0.1" "Sun, April 27, 2014" "DARWIN\ \-\ MAC\ OS\ X"
.SH NAME
.B duplicate
\- creates the disjoint union of a space with itself N times. 
.SH SYNOPSIS
duplicate input_name num_duplicates (=2)
.br
.SH OPTIONS
.SH DESCRIPTION
This algorithm just creates a number of copies of the input space and writes it to
a file called input_name.num_duplicates.asc
.br
.SH VERSION
This documentation describes
.B build_clique
version 0.1
.SH "SEE ALSO"
build_clique, concurrent_homology, duplicate, gpcover, oneskeleton, wghtomet, complex_size,  cover_homology, euler, metowgh, persistence, write_filtration
.br
.I http://ctl.appliedtopology.org site
.SH AUTHOR
.br
.B Ryan H. Lewis
.br
.I \<rhl@stanford.edu\>
