.TH METOWGHT 1 "v\ 0.1" "Sun, April 27, 2014" "DARWIN\ \-\ MAC\ OS\ X"
.SH NAME
.B metowgh
\- Converts a metis graph file to a weighted graph file
.SH SYNOPSIS
metowgh graph
.br
.SH OPTIONS
.SH DESCRIPTION
Writes out a weighted graph file given a metis graph file 
.br
.SH VERSION
This documentation describes
.B build_clique
version 0.1
.SH "SEE ALSO"
build_clique, concurrent_homology, duplicate, gpcover, oneskeleton, wghtomet, complex_size,  cover_homology, euler, metowgh, persistence, write_filtration
.br
.I http://ctl.appliedtopology.org site
.SH AUTHOR
.br
.B Ryan H. Lewis
.br
.I \<rhl@stanford.edu\>
