.TH PERSISTENCE 1 "v\ 0.1" "Sun, April 27, 2014" "DARWIN\ \-\ MAC\ OS\ X"
.SH NAME
.B persistence
\- Computes the persistence homology of a space with a filtration
.SH SYNOPSIS
persistence complex_name.asc
.br
.SH OPTIONS
.SH DESCRIPTION
Presently limited, it assumes a filtration on the input complex. later it will take a filtration file as input. does not yet write the barcodes out. coming soon.
.br
.SH VERSION
This documentation describes
.B persistence
version 0.1
.SH "SEE ALSO"
build_clique, concurrent_homology, duplicate, euler, complex_size, cover_homology, write_filtration, wghtomet, metowgh, gpcover, oneskeleton, concurrent_homology
.br
.I http://ctl.appliedtopology.org site
.SH AUTHOR
.br
.B Ryan H. Lewis
.br
.I \<rhl@stanford.edu\>
